#!/bin/bash

DIR=`mktemp -d`

for f in $*
do
    cp $f $DIR
done

FILE=$DIR/cv.html
sed 's/<a[^>]*>\([^<]*\)<\/a>/<code>\&lt;\1\&gt;<\/code>/g' < cv-nofmts.html > $FILE
wkhtmltopdf $FILE cv.pdf
rm -rf $DIR
